package:
  name: kitsunetsuki-runtime
  version: "0.5"

source:
  path: .

build:
  number: 0
  string: 1588230447

requirements:
  build:
    - panda3d-kitsunetsuki >=1.10.6
    - panda3d-rp-kitsunetsuki >=1.3
    - kcc ==0.1
    - 7za # [win]

about:
  home: https://kitsune.one/
  license: BSD
