package:
  name: kitsunetsuki-runtime
  version: "0.6"

source:
  path: .

build:
  number: 0
  string: 1588230447

requirements:
  build:
    - panda3d
    - kcc
    - 7za # [win]

about:
  home: https://kitsune.one/
  license: BSD
