package:
  name: kcc
  version: "0.1"

source:
  path: .

build:
  number: 0
  string: 1588230447

requirements:
  build:
    - cmake
    - bullet
    - panda3d
  run:
    - panda3d

about:
  home: https://github.com/Yonnji/KITSUNETSUKI-SDK
  license: BSD
