package:
  name: python-blender
  version: "2.82"

source:
  - git_url: git://git.blender.org/blender-addons.git
    git_rev: v2.82a
    folder: blender_extras/release/scripts/addons

  - git_url: git://git.blender.org/blender-addons-contrib.git
    git_rev: v2.82a
    folder: blender_extras/release/scripts/addons_contrib

  - git_url: git://git.blender.org/blender-translations.git
    git_rev: v2.82a
    folder: blender_extras/release/datafiles/locale

  - git_url: git://git.blender.org/blender-dev-tools.git
    git_rev: v2.82a
    folder: blender_extras/source/tools

  - git_url: git://git.blender.org/blender.git
    git_rev: v2.82a
    folder: blender

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14 # [win32]
    folder: lib/windows_vc14 # [win32]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 # [win64]
    folder: lib/win64_vc14 # [win64]

build:
  number: 0
  string: 1588359114

requirements:
  build:
    - cmake
    - python >=3.8
    - requests
    - svn
    - git
    - m2-patch # [win]
    - blender-thirdparty # [unix]
    - bullet
    - llvmdev
  run:
    - python >=3.8

about:
  home: https://www.blender.org/
  license: GPL
