package:
  name: python-blender
  version: "2.81"

source:
  - git_url: git://git.blender.org/blender-addons.git
    git_rev: v2.81
    folder: blender_extras/release/scripts/addons

  - git_url: git://git.blender.org/blender-addons-contrib.git
    git_rev: v2.81
    folder: blender_extras/release/scripts/addons_contrib

  - git_url: git://git.blender.org/blender-translations.git
    git_rev: v2.81
    folder: blender_extras/release/datafiles/locale

  - git_url: git://git.blender.org/blender-dev-tools.git
    git_rev: v2.81
    folder: blender_extras/source/tools

  - git_url: git://git.blender.org/blender.git
    git_rev: v2.81
    folder: blender

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14 # [win32]
    folder: lib/windows_vc14 # [win32]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 # [win64]
    folder: lib/win64_vc14 # [win64]

build:
  number: 0
  string: 1588839915

requirements:
  build:
    - blender-thirdparty # [unix]
    - bullet
    - cmake
    - fontconfig # [unix]
    - freetype # [unix]
    - git
    - jpeg
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libtiff
    - llvmdev
    - m2-patch # [win]
    - python >=3.8
    - requests
    - svn
    - zlib
  run:
    - freetype # [unix]
    - jpeg # [unix]
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libtiff # [unix]
    - python >=3.8
    - zlib # [unix]

about:
  home: https://www.blender.org/
  license: GPL
