package:
  name: bullet
  version: "2.83"

source:
  git_rev: 2.83
  git_url: https://github.com/bulletphysics/bullet3.git

build:
  number: 0
  string: 1600882904

requirements:
  build:
    - cmake

about:
  home: http://bulletphysics.org
  license: Zlib
